server:
  port: 8081
  address: 0.0.0.0

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ems.domain.entity
  configuration:
    # 开启驼峰扫描
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://192.168.159.130:3306/ems?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: CSUims2018
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.ems: debug